# This is a basic workflow to help you get started with Actions

name: Musescore

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # - name: Install Dependencies
      #   run: |
      #     sudo add-apt-repository ppa:mscore-ubuntu/mscore-stable
      #     # sudo apt-get update
      #     sudo apt-get install -y musescore

      - name: Install
        run: |
          echo Downloading musescore!
          wget -O musescore https://cdn.jsdelivr.net/musescore/v3.5.2/MuseScore-3.5.2.312125617-x86_64.AppImage
          chmod +x musescore
          ./musescore --appimage-extract
          rm musescore
          ln -s squashfs-root/bin/musescore-portable musescore

      # Runs a set of commands using the runners shell
      # TODO(eric): Use the json bulk export capability to make this faster
      - name: Generate PDF
        run: |
          mkdir output_pdf/
          for f in *.msc*; 
            do xvfb-run ./musescore --export-score-parts -o output_pdf/${f%.*}.pdf $f; 
          done

      - uses: actions/upload-artifact@v2
        with:
          name: PDF Scores
          path: output_pdf/ # or path/to/artifact

      # Runs a set of commands using the runners shell
      # TODO(eric): Use the json bulk export capability to make this faster
      - name: Generate MP3
        run: |
          mkdir output_mp3/
          for f in *.msc*; 
            do ./musescore -o output_mp3/${f%.*}.mp3 $f; 
          done

      - uses: actions/upload-artifact@v2
        with:
          name: MP3
          path: output_mp3/ # or path/to/artifact
